"""Central constants for environment variable names and defaults.

Keeping all tunables and their default values in one place ensures DRY and
readability across modules (config, audio, drive, CDK).
"""
from __future__ import annotations

# Environment variable names
ENV_SERVICE_ACCOUNT_FILE = "SERVICE_ACCOUNT_FILE"
ENV_DRIVE_FOLDER_ID = "DRIVE_FOLDER_ID"
ENV_EMAIL_TO = "EMAIL_TO"
ENV_GMAIL_SENDER_EMAIL = "GMAIL_SENDER_EMAIL"
ENV_GMAIL_APP_PASSWORD = "GMAIL_APP_PASSWORD"
ENV_RUNPOD_API_KEY = "RUNPOD_API_KEY"
ENV_RUNPOD_ENDPOINT_ID = "RUNPOD_ENDPOINT_ID"
ENV_CONFIG_PATH = "CONFIG_PATH"
ENV_MAX_SEGMENT_CONCURRENCY = "MAX_SEGMENT_CONCURRENCY"
ENV_SEG_SECONDS = "SEG_SECONDS"
ENV_SKIP_DRIVE = "SKIP_DRIVE"
ENV_BYPASS_SPLIT = "BYPASS_SPLIT"
ENV_TIME_WINDOW_ENABLED = "TIME_WINDOW_ENABLED"
ENV_SCHEDULE_START_HOUR = "SCHEDULE_START_HOUR"
ENV_SCHEDULE_END_HOUR = "SCHEDULE_END_HOUR"
ENV_SCHEDULE_DAYS = "SCHEDULE_DAYS"
ENV_SCHEDULE_TIMEZONE = "SCHEDULE_TIMEZONE"
ENV_FFMPEG_PATH = "FFMPEG_PATH"
ENV_AUDIO_EXTENSIONS = "AUDIO_EXTENSIONS"
ENV_MAX_SEGMENT_RETRIES = "MAX_SEGMENT_RETRIES"
ENV_BALANCE_ALERT_VALUE = "BALANCE_ALERT_VALUE"
ENV_ADD_RANDOM_PERSONAL_MESSAGE = "ADD_RANDOM_PERSONAL_MESSAGE"
ENV_MAX_PAYLOAD_SIZE = "MAX_PAYLOAD_SIZE"
ENV_MAX_SPLIT_DEPTH = "MAX_SPLIT_DEPTH"
ENV_MAX_SEGMENT_SIZE = "MAX_SEGMENT_SIZE"
# CDK-specific optional
ENV_FFMPEG_LAYER_ARN = "FFMPEG_LAYER_ARN"
# Tests/E2E
ENV_RUNPOD_E2E = "RUNPOD_E2E"

# Defaults
DEFAULT_CONFIG_PATH_REL = "config.json"
DEFAULT_AUDIO_EXTENSIONS = ".m4a,.wav,.mp3,.ogg,.flac,.aac,.wma,.m4b,.aiff,.aif,.opus"
DEFAULT_FFMPEG_PATH = "ffmpeg"  # overridden to /opt/bin/ffmpeg in Lambda via env
DEFAULT_MAX_SEGMENT_CONCURRENCY = 2
DEFAULT_SEG_SECONDS = 8 * 60
DEFAULT_SKIP_DRIVE = False
DEFAULT_BYPASS_SPLIT = False
DEFAULT_TIME_WINDOW_ENABLED = True
DEFAULT_SCHEDULE_START_HOUR = 8
DEFAULT_SCHEDULE_END_HOUR = 22
DEFAULT_SCHEDULE_DAYS = "SUN-SAT"
DEFAULT_SCHEDULE_TIMEZONE = "UTC"
DEFAULT_ADD_RANDOM_PERSONAL_MESSAGE = True
DEFAULT_MAX_SEGMENT_RETRIES = 2
DEFAULT_BALANCE_ALERT_VALUE = 2.0
DEFAULT_MAX_PAYLOAD_SIZE = 9 * 1024 * 1024  # 9MB
DEFAULT_MAX_SPLIT_DEPTH = 3
DEFAULT_MAX_SEGMENT_SIZE = 8 * 1024 * 1024  # 8MB

__all__ = [name for name in globals().keys() if name.startswith("ENV_") or name.startswith("DEFAULT_")]
